import type {
  CineCapsula,
  Director,
  HorarioFuncion,
  Pelicula,
  TipoCine,
} from "./types";

// Datos iniciales completos extraídos de proyecto.sql (NO SE OMITE NINGÚN REGISTRO)

export const INITIAL_TIPO_CINE: TipoCine[] = [
  { id_tipo: 1, nombre_tipo: "Cine de Autor" },
  { id_tipo: 2, nombre_tipo: "Cine de Culto" },
  { id_tipo: 3, nombre_tipo: "5 Estrellas" },
  { id_tipo: 4, nombre_tipo: "Documental" },
  { id_tipo: 5, nombre_tipo: "Cine Mexicano Clásico" },
  { id_tipo: 6, nombre_tipo: "Ciclo de Cine Negro" },
  { id_tipo: 7, nombre_tipo: "Retrospectiva" },
  { id_tipo: 8, nombre_tipo: "Animación Experimental" },
];

export const INITIAL_DIRECTORES: Director[] = [
  { id_director: 1, nombre_completo: "Pedro Almodóvar" },
  { id_director: 2, nombre_completo: "Akira Kurosawa" },
  { id_director: 3, nombre_completo: "Guillermo del Toro" },
  { id_director: 4, nombre_completo: "Alfred Hitchcock" },
  { id_director: 5, nombre_completo: "Stanley Kubrick" },
  { id_director: 6, nombre_completo: "Sofía Coppola" },
  { id_director: 7, nombre_completo: "Ingmar Bergman" },
  { id_director: 8, nombre_completo: "Luis Buñuel" },
  { id_director: 9, nombre_completo: "Denis Villeneuve" },
  { id_director: 10, nombre_completo: "Agnès Varda" },
  { id_director: 11, nombre_completo: "Quentin Tarantino" },
  { id_director: 12, nombre_completo: "Alfonso Cuarón" },
];

export const INITIAL_PELICULAS: Pelicula[] = [
  {
    id_pelicula: 1,
    titulo_original: "Roma",
    titulo_espanol: "Roma",
    sinopsis:
      "Crónica de un año turbulento en la vida de una familia de clase media en la Ciudad de México de principios de los 70.",
    anio_lanzamiento: 2018,
    pais_origen: "México",
    duracion_minutos: 135,
    ficha_tecnica_resumen:
      "Fotografía en blanco y negro, Yalitza Aparicio, Marina de Tavira.",
    id_director: 12,
    id_tipo_cine: 1,
  },
  {
    id_pelicula: 2,
    titulo_original: "Yojimbo",
    titulo_espanol: "Yojimbo, el mercenario",
    sinopsis:
      "Un samurái errante llega a un pueblo dividido por dos bandas criminales y decide enfrentar a ambas.",
    anio_lanzamiento: 1961,
    pais_origen: "Japón",
    duracion_minutos: 110,
    ficha_tecnica_resumen:
      "Toshiro Mifune en un papel icónico, influencia en el western spaghetti.",
    id_director: 2,
    id_tipo_cine: 6,
  },
  {
    id_pelicula: 3,
    titulo_original: "2001: A Space Odyssey",
    titulo_espanol: "2001: Odisea del Espacio",
    sinopsis:
      "La evolución humana y la inteligencia artificial en un viaje a Júpiter.",
    anio_lanzamiento: 1968,
    pais_origen: "Reino Unido/EE. UU.",
    duracion_minutos: 149,
    ficha_tecnica_resumen:
      "Efectos visuales revolucionarios, banda sonora clásica.",
    id_director: 5,
    id_tipo_cine: 2,
  },
  {
    id_pelicula: 4,
    titulo_original: "El laberinto del fauno",
    titulo_espanol: "El laberinto del fauno",
    sinopsis:
      "Una niña se adentra en un mundo mágico para escapar de la crueldad de la posguerra española.",
    anio_lanzamiento: 2006,
    pais_origen: "México/España",
    duracion_minutos: 118,
    ficha_tecnica_resumen: "Fantasía oscura, diseño de criaturas.",
    id_director: 3,
    id_tipo_cine: 3,
  },
  {
    id_pelicula: 5,
    titulo_original: "Vertigo",
    titulo_espanol: "Vértigo",
    sinopsis:
      "Un detective retirado con miedo a las alturas investiga la obsesión de un amigo por su esposa.",
    anio_lanzamiento: 1958,
    pais_origen: "EE. UU.",
    duracion_minutos: 128,
    ficha_tecnica_resumen: "Técnica de zoom in/dolly out, Kim Novak.",
    id_director: 4,
    id_tipo_cine: 3,
  },
  {
    id_pelicula: 6,
    titulo_original: "Pulp Fiction",
    titulo_espanol: "Tiempos Violentos",
    sinopsis:
      "Historias cruzadas de gánsteres, un boxeador, y ladrones de poca monta en Los Ángeles.",
    anio_lanzamiento: 1994,
    pais_origen: "EE. UU.",
    duracion_minutos: 154,
    ficha_tecnica_resumen:
      "Diálogos ingeniosos, estructura narrativa no lineal.",
    id_director: 11,
    id_tipo_cine: 2,
  },
  {
    id_pelicula: 7,
    titulo_original: "El ángel exterminador",
    titulo_espanol: "El ángel exterminador",
    sinopsis:
      "Un grupo de burgueses se encuentra misteriosamente incapaz de salir de una habitación después de una cena.",
    anio_lanzamiento: 1962,
    pais_origen: "México",
    duracion_minutos: 95,
    ficha_tecnica_resumen:
      "Sátira surrealista de la burguesía, crítica social.",
    id_director: 8,
    id_tipo_cine: 1,
  },
  {
    id_pelicula: 8,
    titulo_original: "The Piano",
    titulo_espanol: "El Piano",
    sinopsis:
      "Una mujer muda y su hija se trasladan a Nueva Zelanda para un matrimonio arreglado, llevando consigo solo su piano.",
    anio_lanzamiento: 1993,
    pais_origen: "Nueva Zelanda",
    duracion_minutos: 121,
    ficha_tecnica_resumen:
      "Jane Campion, Holly Hunter, banda sonora memorable.",
    id_director: 6,
    id_tipo_cine: 7,
  },
  {
    id_pelicula: 9,
    titulo_original: "Persona",
    titulo_espanol: "Persona",
    sinopsis:
      "Una enfermera cuida a una actriz de teatro que ha enmudecido. Sus personalidades se mezclan.",
    anio_lanzamiento: 1966,
    pais_origen: "Suecia",
    duracion_minutos: 85,
    ficha_tecnica_resumen: "Exploración psicológica profunda, planos intensos.",
    id_director: 7,
    id_tipo_cine: 1,
  },
  {
    id_pelicula: 10,
    titulo_original: "Oldboy",
    titulo_espanol: "Oldboy",
    sinopsis:
      "Un hombre es secuestrado y retenido durante 15 años sin saber la razón, y es liberado con un límite de tiempo para encontrar a su captor.",
    anio_lanzamiento: 2003,
    pais_origen: "Corea del Sur",
    duracion_minutos: 120,
    ficha_tecnica_resumen: "Escena de lucha con martillo, trama de venganza.",
    id_director: 2,
    id_tipo_cine: 2,
  },
  {
    id_pelicula: 11,
    titulo_original: "The Lighthouse",
    titulo_espanol: "El Faro",
    sinopsis:
      "Dos fareros se enfrentan a la locura y los elementos en una remota isla de Nueva Inglaterra en la década de 1890.",
    anio_lanzamiento: 2019,
    pais_origen: "EE. UU.",
    duracion_minutos: 109,
    ficha_tecnica_resumen: "Blanco y negro, formato de aspecto cuadrado.",
    id_director: 5,
    id_tipo_cine: 4,
  },
  {
    id_pelicula: 12,
    titulo_original: "Fargo",
    titulo_espanol: "Fargo",
    sinopsis:
      "Un vendedor de autos contrata a dos matones para secuestrar a su esposa, lo que desata una serie de asesinatos.",
    anio_lanzamiento: 1996,
    pais_origen: "EE. UU.",
    duracion_minutos: 98,
    ficha_tecnica_resumen: "Hermanos Coen, humor negro, policía embarazada.",
    id_director: 11,
    id_tipo_cine: 3,
  },
  {
    id_pelicula: 13,
    titulo_original: "Hable con ella",
    titulo_espanol: "Hable con ella",
    sinopsis:
      "Dos hombres se conocen cuidando a dos mujeres en coma en un hospital.",
    anio_lanzamiento: 2002,
    pais_origen: "España",
    duracion_minutos: 112,
    ficha_tecnica_resumen: "Temas de soledad y comunicación, música.",
    id_director: 1,
    id_tipo_cine: 1,
  },
  {
    id_pelicula: 14,
    titulo_original: "Trainspotting",
    titulo_espanol: "Trainspotting",
    sinopsis:
      "La vida de un grupo de jóvenes adictos a la heroína en Edimburgo.",
    anio_lanzamiento: 1996,
    pais_origen: "Reino Unido",
    duracion_minutos: 94,
    ficha_tecnica_resumen: "Estilo visual frenético, Ewan McGregor.",
    id_director: 6,
    id_tipo_cine: 2,
  },
  {
    id_pelicula: 15,
    titulo_original: "Amélie",
    titulo_espanol: "El fabuloso destino de Amélie Poulain",
    sinopsis:
      "Una joven de París decide cambiar las vidas de las personas que la rodean para bien.",
    anio_lanzamiento: 2001,
    pais_origen: "Francia",
    duracion_minutos: 122,
    ficha_tecnica_resumen: "Colores saturados, París idealizado.",
    id_director: 10,
    id_tipo_cine: 3,
  },
  {
    id_pelicula: 16,
    titulo_original: "La isla mínima",
    titulo_espanol: "La isla mínima",
    sinopsis:
      "Dos detectives de Madrid son enviados a un pueblo remoto para investigar la desaparición de dos adolescentes.",
    anio_lanzamiento: 2014,
    pais_origen: "España",
    duracion_minutos: 105,
    ficha_tecnica_resumen: "Thriller oscuro, ambientación en los pantanos.",
    id_director: 9,
    id_tipo_cine: 6,
  },
  {
    id_pelicula: 17,
    titulo_original: "Parasite",
    titulo_espanol: "Parásitos",
    sinopsis:
      "Una familia pobre se infiltra en la vida de una familia rica con consecuencias inesperadas.",
    anio_lanzamiento: 2019,
    pais_origen: "Corea del Sur",
    duracion_minutos: 132,
    ficha_tecnica_resumen: "Crítica social, cambio de género.",
    id_director: 3,
    id_tipo_cine: 3,
  },
  {
    id_pelicula: 18,
    titulo_original: "Midnight in Paris",
    titulo_espanol: "Medianoche en París",
    sinopsis: "Un escritor viaja en el tiempo a los años 20 en París.",
    anio_lanzamiento: 2011,
    pais_origen: "EE. UU.",
    duracion_minutos: 94,
    ficha_tecnica_resumen: "Woody Allen, nostalgia.",
    id_director: 12,
    id_tipo_cine: 7,
  },
  {
    id_pelicula: 19,
    titulo_original: "Mad Max: Fury Road",
    titulo_espanol: "Mad Max: Furia en el camino",
    sinopsis:
      "En un futuro post-apocalíptico, una mujer lidera un grupo a través del desierto para escapar de un tirano.",
    anio_lanzamiento: 2015,
    pais_origen: "Australia",
    duracion_minutos: 120,
    ficha_tecnica_resumen: "Acción continua, efectos prácticos.",
    id_director: 11,
    id_tipo_cine: 2,
  },
  {
    id_pelicula: 20,
    titulo_original: "Pans Labyrinth",
    titulo_espanol: "El laberinto del fauno",
    sinopsis: "Versión alternativa de El laberinto del Fauno.",
    anio_lanzamiento: 2006,
    pais_origen: "México/España",
    duracion_minutos: 118,
    ficha_tecnica_resumen: "Fantasía y guerra.",
    id_director: 3,
    id_tipo_cine: 3,
  },
  {
    id_pelicula: 21,
    titulo_original: "The Godfather",
    titulo_espanol: "El Padrino",
    sinopsis: "La saga de la familia Corleone.",
    anio_lanzamiento: 1972,
    pais_origen: "EE. UU.",
    duracion_minutos: 175,
    ficha_tecnica_resumen: "Obra maestra del cine de gánsteres.",
    id_director: 4,
    id_tipo_cine: 3,
  },
  {
    id_pelicula: 22,
    titulo_original: "Requiem for a Dream",
    titulo_espanol: "Réquiem por un sueño",
    sinopsis: "Cuatro vidas en Brooklyn se arruinan por adicciones.",
    anio_lanzamiento: 2000,
    pais_origen: "EE. UU.",
    duracion_minutos: 102,
    ficha_tecnica_resumen: "Montaje rápido, impacto visual.",
    id_director: 6,
    id_tipo_cine: 2,
  },
  {
    id_pelicula: 23,
    titulo_original: "Babel",
    titulo_espanol: "Babel",
    sinopsis:
      "Historias interconectadas de personas de distintas culturas y países.",
    anio_lanzamiento: 2006,
    pais_origen: "EE. UU.",
    duracion_minutos: 143,
    ficha_tecnica_resumen: "Narrativa coral, fotografía.",
    id_director: 12,
    id_tipo_cine: 1,
  },
  {
    id_pelicula: 24,
    titulo_original: "Drive",
    titulo_espanol: "Drive",
    sinopsis:
      "Un conductor de escape que trabaja en Hollywood se enamora de su vecina.",
    anio_lanzamiento: 2011,
    pais_origen: "EE. UU.",
    duracion_minutos: 100,
    ficha_tecnica_resumen: "Estética neon, banda sonora ochentera.",
    id_director: 9,
    id_tipo_cine: 2,
  },
  {
    id_pelicula: 25,
    titulo_original: "Spirited Away",
    titulo_espanol: "El viaje de Chihiro",
    sinopsis: "Una niña se adentra en un mundo mágico de espíritus.",
    anio_lanzamiento: 2001,
    pais_origen: "Japón",
    duracion_minutos: 125,
    ficha_tecnica_resumen: "Animación japonesa, Miyazaki.",
    id_director: 2,
    id_tipo_cine: 8,
  },
  {
    id_pelicula: 26,
    titulo_original: "Fanny y Alexander",
    titulo_espanol: "Fanny y Alexander",
    sinopsis:
      "Dos hermanos experimentan la vida a través de los ojos de la infancia en la Suecia de principios del siglo XX.",
    anio_lanzamiento: 1982,
    pais_origen: "Suecia",
    duracion_minutos: 188,
    ficha_tecnica_resumen: "Drama familiar, Bergman.",
    id_director: 7,
    id_tipo_cine: 1,
  },
  {
    id_pelicula: 27,
    titulo_original: "Blue Velvet",
    titulo_espanol: "Terciopelo Azul",
    sinopsis: "Un joven descubre un lado oscuro de su tranquilo pueblo.",
    anio_lanzamiento: 1986,
    pais_origen: "EE. UU.",
    duracion_minutos: 120,
    ficha_tecnica_resumen: "David Lynch, surrealismo.",
    id_director: 5,
    id_tipo_cine: 2,
  },
  {
    id_pelicula: 28,
    titulo_original: "Close-Up",
    titulo_espanol: "Close-Up",
    sinopsis: "Un hombre es juzgado por hacerse pasar por un director de cine.",
    anio_lanzamiento: 1990,
    pais_origen: "Irán",
    duracion_minutos: 98,
    ficha_tecnica_resumen: "Documental/ficción, Abbas Kiarostami.",
    id_director: 10,
    id_tipo_cine: 4,
  },
  {
    id_pelicula: 29,
    titulo_original: "El discreto encanto de la burguesía",
    titulo_espanol: "El discreto encanto de la burguesía",
    sinopsis:
      "Un grupo de burgueses intenta cenar sin éxito, siendo interrumpidos por eventos surrealistas.",
    anio_lanzamiento: 1972,
    pais_origen: "Francia/España",
    duracion_minutos: 102,
    ficha_tecnica_resumen: "Sátira, Buñuel.",
    id_director: 8,
    id_tipo_cine: 1,
  },
  {
    id_pelicula: 30,
    titulo_original: "Traffic",
    titulo_espanol: "Traffic",
    sinopsis:
      "Historias cruzadas sobre el narcotráfico y sus efectos en varios niveles sociales.",
    anio_lanzamiento: 2000,
    pais_origen: "EE. UU.",
    duracion_minutos: 147,
    ficha_tecnica_resumen:
      "Steven Soderbergh, fotografía con tonos diferentes.",
    id_director: 4,
    id_tipo_cine: 3,
  },
];

export const INITIAL_HORARIOS: HorarioFuncion[] = [
  {
    id_horario: 1,
    fecha_hora_transmision: "2025-12-15 18:00:00",
    id_pelicula: 1,
  },
  {
    id_horario: 2,
    fecha_hora_transmision: "2025-12-15 20:30:00",
    id_pelicula: 2,
  },
  {
    id_horario: 3,
    fecha_hora_transmision: "2025-12-16 17:00:00",
    id_pelicula: 3,
  },
  {
    id_horario: 4,
    fecha_hora_transmision: "2025-12-16 22:00:00",
    id_pelicula: 4,
  },
  {
    id_horario: 5,
    fecha_hora_transmision: "2025-12-17 19:30:00",
    id_pelicula: 5,
  },
  {
    id_horario: 6,
    fecha_hora_transmision: "2025-12-17 16:00:00",
    id_pelicula: 6,
  },
  {
    id_horario: 7,
    fecha_hora_transmision: "2025-12-18 18:00:00",
    id_pelicula: 7,
  },
  {
    id_horario: 8,
    fecha_hora_transmision: "2025-12-18 21:00:00",
    id_pelicula: 8,
  },
  {
    id_horario: 9,
    fecha_hora_transmision: "2025-12-19 19:00:00",
    id_pelicula: 9,
  },
  {
    id_horario: 10,
    fecha_hora_transmision: "2025-12-19 16:00:00",
    id_pelicula: 10,
  },
  {
    id_horario: 11,
    fecha_hora_transmision: "2025-12-20 17:30:00",
    id_pelicula: 11,
  },
  {
    id_horario: 12,
    fecha_hora_transmision: "2025-12-20 20:45:00",
    id_pelicula: 12,
  },
  {
    id_horario: 13,
    fecha_hora_transmision: "2025-12-21 16:30:00",
    id_pelicula: 13,
  },
  {
    id_horario: 14,
    fecha_hora_transmision: "2025-12-21 19:45:00",
    id_pelicula: 14,
  },
  {
    id_horario: 15,
    fecha_hora_transmision: "2025-12-22 17:00:00",
    id_pelicula: 15,
  },
  {
    id_horario: 16,
    fecha_hora_transmision: "2025-12-22 21:30:00",
    id_pelicula: 16,
  },
  {
    id_horario: 17,
    fecha_hora_transmision: "2025-12-23 18:30:00",
    id_pelicula: 17,
  },
  {
    id_horario: 18,
    fecha_hora_transmision: "2025-12-23 20:00:00",
    id_pelicula: 18,
  },
  {
    id_horario: 19,
    fecha_hora_transmision: "2025-12-24 16:00:00",
    id_pelicula: 19,
  },
  {
    id_horario: 20,
    fecha_hora_transmision: "2025-12-24 19:00:00",
    id_pelicula: 20,
  },
  {
    id_horario: 21,
    fecha_hora_transmision: "2025-12-25 17:30:00",
    id_pelicula: 21,
  },
  {
    id_horario: 22,
    fecha_hora_transmision: "2025-12-25 22:00:00",
    id_pelicula: 22,
  },
  {
    id_horario: 23,
    fecha_hora_transmision: "2025-12-26 18:00:00",
    id_pelicula: 23,
  },
  {
    id_horario: 24,
    fecha_hora_transmision: "2025-12-26 20:15:00",
    id_pelicula: 24,
  },
  {
    id_horario: 25,
    fecha_hora_transmision: "2025-12-27 16:45:00",
    id_pelicula: 25,
  },
  {
    id_horario: 26,
    fecha_hora_transmision: "2025-12-27 19:30:00",
    id_pelicula: 26,
  },
  {
    id_horario: 27,
    fecha_hora_transmision: "2025-12-28 17:00:00",
    id_pelicula: 27,
  },
  {
    id_horario: 28,
    fecha_hora_transmision: "2025-12-28 20:00:00",
    id_pelicula: 28,
  },
  {
    id_horario: 29,
    fecha_hora_transmision: "2025-12-29 18:30:00",
    id_pelicula: 29,
  },
  {
    id_horario: 30,
    fecha_hora_transmision: "2025-12-29 21:45:00",
    id_pelicula: 30,
  },
];

export const INITIAL_CAPSULAS: CineCapsula[] = [
  {
    id_capsula: 1,
    titulo_capsula: "Entrevista con Alfonso Cuarón",
    descripcion: "El director habla sobre el proceso creativo de Roma.",
    duracion_minutos: 8,
    fecha_transmision: "2025-12-15 17:45:00",
    id_pelicula: 1,
  },
  {
    id_capsula: 2,
    titulo_capsula: "Análisis Visual: Yojimbo",
    descripcion:
      "Estudio sobre la composición de planos en el film de Kurosawa.",
    duracion_minutos: 5,
    fecha_transmision: "2025-12-15 20:00:00",
    id_pelicula: 2,
  },
  {
    id_capsula: 3,
    titulo_capsula: "Detrás de Escena: 2001",
    descripcion: "Cómo se lograron los efectos especiales sin computadoras.",
    duracion_minutos: 12,
    fecha_transmision: "2025-12-16 16:45:00",
    id_pelicula: 3,
  },
  {
    id_capsula: 4,
    titulo_capsula: "Mini-Doc: La Guerra Civil Española",
    descripcion: "Contexto histórico para El laberinto del fauno.",
    duracion_minutos: 10,
    fecha_transmision: "2025-12-16 21:45:00",
    id_pelicula: 4,
  },
  {
    id_capsula: 5,
    titulo_capsula: "Maestros del Suspense: Hitchcock",
    descripcion: "Especial sobre la técnica de Alfred Hitchcock en Vértigo.",
    duracion_minutos: 7,
    fecha_transmision: "2025-12-17 19:00:00",
    id_pelicula: 5,
  },
  {
    id_capsula: 6,
    titulo_capsula: "La Música de Pulp Fiction",
    descripcion: "Análisis de la banda sonora y su influencia en el cine.",
    duracion_minutos: 6,
    fecha_transmision: "2025-12-17 15:45:00",
    id_pelicula: 6,
  },
  {
    id_capsula: 7,
    titulo_capsula: "Buñuel: El Surrealismo Mexicano",
    descripcion: "Especial sobre la etapa de Buñuel en México.",
    duracion_minutos: 8,
    fecha_transmision: "2025-12-18 17:45:00",
    id_pelicula: 7,
  },
  {
    id_capsula: 8,
    titulo_capsula: "Moda y Cine: The Piano",
    descripcion: "La importancia del vestuario en la película.",
    duracion_minutos: 5,
    fecha_transmision: "2025-12-18 20:45:00",
    id_pelicula: 8,
  },
  {
    id_capsula: 9,
    titulo_capsula: "Bergman y la Identidad",
    descripcion: "Reflexión sobre los temas de identidad en Persona.",
    duracion_minutos: 9,
    fecha_transmision: "2025-12-19 18:45:00",
    id_pelicula: 9,
  },
  {
    id_capsula: 10,
    titulo_capsula: "Venganza en el Cine Coreano",
    descripcion: "Un vistazo a las películas de venganza tras Oldboy.",
    duracion_minutos: 7,
    fecha_transmision: "2025-12-19 15:45:00",
    id_pelicula: 10,
  },
  {
    id_capsula: 11,
    titulo_capsula: "Especial: Cine de Autor",
    descripcion: "Análisis de las características del cine de autor.",
    duracion_minutos: 10,
    fecha_transmision: "2025-12-20 17:00:00",
    id_pelicula: null,
  },
  {
    id_capsula: 12,
    titulo_capsula: "La Fotografía en Blanco y Negro",
    descripcion: "Técnicas de fotografía.",
    duracion_minutos: 6,
    fecha_transmision: "2025-12-20 20:30:00",
    id_pelicula: null,
  },
  {
    id_capsula: 13,
    titulo_capsula: "Cine y Derechos Humanos",
    descripcion: "Documental sobre el impacto social.",
    duracion_minutos: 15,
    fecha_transmision: "2025-12-21 16:15:00",
    id_pelicula: null,
  },
  {
    id_capsula: 14,
    titulo_capsula: "Detrás de Amélie: París",
    descripcion: "Los escenarios y la inspiración de la película.",
    duracion_minutos: 7,
    fecha_transmision: "2025-12-22 16:45:00",
    id_pelicula: 15,
  },
  {
    id_capsula: 15,
    titulo_capsula: "El Cine Negro Español",
    descripcion: "Las influencias de La isla mínima.",
    duracion_minutos: 8,
    fecha_transmision: "2025-12-22 21:15:00",
    id_pelicula: 16,
  },
  {
    id_capsula: 16,
    titulo_capsula: "Clase Social en Parasite",
    descripcion: "Cómo la película aborda la división de clases.",
    duracion_minutos: 9,
    fecha_transmision: "2025-12-23 18:15:00",
    id_pelicula: 17,
  },
  {
    id_capsula: 17,
    titulo_capsula: "Woody Allen y el Viaje en el Tiempo",
    descripcion: "El uso de la fantasía en Midnight in Paris.",
    duracion_minutos: 6,
    fecha_transmision: "2025-12-23 19:45:00",
    id_pelicula: 18,
  },
  {
    id_capsula: 18,
    titulo_capsula: "Efectos Prácticos en Furia",
    descripcion: "El rodaje de Mad Max: Fury Road.",
    duracion_minutos: 11,
    fecha_transmision: "2025-12-24 15:45:00",
    id_pelicula: 19,
  },
  {
    id_capsula: 19,
    titulo_capsula: "Mitología en El Laberinto",
    descripcion: "Los símbolos y referencias mitológicas en la película.",
    duracion_minutos: 8,
    fecha_transmision: "2025-12-24 18:45:00",
    id_pelicula: 20,
  },
  {
    id_capsula: 20,
    titulo_capsula: "La Trilogía del Padrino",
    descripcion: "El impacto cultural y narrativo de la saga.",
    duracion_minutos: 10,
    fecha_transmision: "2025-12-25 17:15:00",
    id_pelicula: 21,
  },
  {
    id_capsula: 21,
    titulo_capsula: "Adicciones en el Cine",
    descripcion: "Representación de las adicciones en Réquiem por un Sueño.",
    duracion_minutos: 7,
    fecha_transmision: "2025-12-25 21:45:00",
    id_pelicula: 22,
  },
  {
    id_capsula: 22,
    titulo_capsula: "La Construcción de Babel",
    descripcion: "Cómo se entrelazan las narrativas.",
    duracion_minutos: 9,
    fecha_transmision: "2025-12-26 17:45:00",
    id_pelicula: 23,
  },
  {
    id_capsula: 23,
    titulo_capsula: "Estética Neon: Drive",
    descripcion: "El estilo visual y la música de la película.",
    duracion_minutos: 6,
    fecha_transmision: "2025-12-26 20:00:00",
    id_pelicula: 24,
  },
  {
    id_capsula: 24,
    titulo_capsula: "Mundo de Espíritus: Chihiro",
    descripcion: "Análisis de la animación japonesa.",
    duracion_minutos: 8,
    fecha_transmision: "2025-12-27 16:30:00",
    id_pelicula: 25,
  },
  {
    id_capsula: 25,
    titulo_capsula: "Cine y Familia: Fanny y Alexander",
    descripcion: "La autobiografía de Bergman.",
    duracion_minutos: 10,
    fecha_transmision: "2025-12-27 19:15:00",
    id_pelicula: 26,
  },
  {
    id_capsula: 26,
    titulo_capsula: "El Misterio de Blue Velvet",
    descripcion: "El tono surrealista y el terror psicológico.",
    duracion_minutos: 7,
    fecha_transmision: "2025-12-28 16:45:00",
    id_pelicula: 27,
  },
  {
    id_capsula: 27,
    titulo_capsula: "Cine Iraní Contemporáneo",
    descripcion: "El estilo de Close-Up.",
    duracion_minutos: 9,
    fecha_transmision: "2025-12-28 19:45:00",
    id_pelicula: 28,
  },
  {
    id_capsula: 28,
    titulo_capsula: "Sátira Social en Buñuel",
    descripcion: "El uso del humor negro en El discreto encanto...",
    duracion_minutos: 6,
    fecha_transmision: "2025-12-29 18:15:00",
    id_pelicula: 29,
  },
  {
    id_capsula: 29,
    titulo_capsula: "Política y Tráfico",
    descripcion: "El enfoque político de la película Traffic.",
    duracion_minutos: 11,
    fecha_transmision: "2025-12-29 21:30:00",
    id_pelicula: 30,
  },
  {
    id_capsula: 30,
    titulo_capsula: "Especial: El Catálogo de Cinema 22",
    descripcion: "Un resumen de la programación mensual.",
    duracion_minutos: 15,
    fecha_transmision: "2025-12-30 19:00:00",
    id_pelicula: null,
  },
];
